#ifndef SYMBOL_TABLE_PRINTER_H
#define SYMBOL_TABLE_PRINTER_H

#include <string>

// -----------------------------------------------------
// Function Declarations
// -----------------------------------------------------

// Prints all tokens generated by the lexer along with
// their type, line/column position, and symbol/lexeme value.
void printTokens(const std::string& input);

#endif // SYMBOL_TABLE_PRINTER_H
